[tool.poetry]
name = "microc-app"
version = "0.1.0"
description = "MicroC interaction Streamlit App"
authors = ["You"]

[tool.poetry.dependencies]
streamlit = "*"
pyGenomeTracks = "*"
matplotlib = "<=3.6.2"
